### ISSUE TITLE
Auto Loaders don't  use products_id for pages (Fixed)

### ISSUE THREAD

**Issue by RedBaron2** [zepluf/plugin-riCjLoader#4]
I edited your core code (sorry) but by adding a global to your function, along with a simple loop. I was able to get autoloader for specific products and then a global auto loader for main_pages like product_info (which is core functionality)
Below is my edit of your function :

function setCurrentPageBase(){
if(!$this->get('admin')){
global $current_page_base, $this_is_home_page, $product_match;
// RB added the global $product_match
// set current page
if($this_is_home_page)
$this->current_page_base = 'index_home';
elseif($current_page_base == 'index'){
if(isset($_GET['cPath']))
$this->current_page_base = 'index_category';
elseif(isset($_GET['manufacturers_id']))
$this->current_page_base = 'index_manufacturer';
}
else {
// bof RB Edit
foreach ($product_match as &$value) {
if ( $_GET['products_id'] == $value ) {
return $this->current_page_base = $value;
} else {
$this->current_page_base = $current_page_base;
}
}
unset($value); // break the reference with the last element
// eof RB edit
}

//  $this->current_page_base = $current_page_base;
}
else{
$this->current_page_base = preg_replace('/.php/','',substr(strrchr($_SERVER['PHP_SELF'],'/'),1),1);
}
}

This works for the function of finding the specific product that will need what is in the autoloader/loader*.php file. It also loads all pages that are main_page=product_info if they don't match my specific product. The global is stored in the english.php file for Your_Template.
## I do have one question of how to load 'cdn' via the auto loaders. Thanks for the great program and keep up the good work.

Red Baron

**Comment by yellow1912** [comment]
with the new version, cdn can be set via the config.yml, we will have a tutorial on this soon
